# -*- coding: utf-8 -*-
"""Get_min_max.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jwsskXTmF4521sJRrO1Ci1gnFRhqne5O
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

filename = next(iter(uploaded))
data = pd.read_csv(filename,delimiter=", ", engine='python')

data

def minMax(x):
    return pd.Series(index=['min','max'],data=[x.min(),x.max()])


data = data.apply(minMax)
data

min = data.iloc[:1, :]
max = data.iloc[1:, :]

import numpy as np

f = open("min.txt", "w")
np.savetxt("min.txt", min.values, delimiter='\n')
f.close()

f = open("max.txt", "w")
np.savetxt("max.txt", max.values, delimiter='\n')
f.close()

from google.colab import files
files.download('min.txt')
files.download('max.txt')